# Generated by Django 2.2.5 on 2019-12-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salary_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='total',
        ),
    ]
