# Generated by Django 2.2.5 on 2019-12-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191216_0100'),
        ('salary', '0003_remove_salary_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.IntegerField(default=0)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
    ]
