# Generated by Django 2.2.5 on 2019-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(verbose_name=10)),
                ('qualification', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('pannum', models.CharField(max_length=40)),
                ('aadhar', models.IntegerField(verbose_name=12)),
                ('laddress', models.CharField(max_length=60)),
                ('paddress', models.CharField(max_length=60)),
            ],
        ),
    ]
