# Generated by Django 2.2.5 on 2019-12-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191211_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='dataofjoin',
            new_name='dateofjoin',
        ),
    ]
