# Generated by Django 2.2.5 on 2019-12-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191211_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
